name: Docker Build  # 工作流名称
on:
  # 触发条件：与 Python 测试一致（同步验证）
  push:
    branches: ["dev", "feature/**"]
  pull_request:
    branches: ["dev"]
jobs:
  build:
    runs-on: ubuntu-latest  # 运行环境：Ubuntu 服务器
    steps:
      - name: Checkout code  # 步骤1：拉取仓库代码
        uses: actions/checkout@v4
      - name: Set up Docker Buildx  # 步骤2：配置 Docker 构建工具
        uses: docker/setup-buildx-action@v3
      - name: Build Docker image  # 步骤3：构建镜像（暂不推送）
        uses: docker/build-push-action@v5
        with:
          context: .  # 构建上下文：当前目录
          push: false  # 若需推送镜像仓库，设为 true 并添加登录步骤
          tags: my-app:latest  # 镜像标签（可自定义，如 "username/my-app:${{ github.sha }}"）
