name: Python Tests  # 工作流名称
on:
  # 触发条件：推送至 dev/feature/* 分支，或向 dev 分支提 PR
  push:
    branches: ["dev", "feature/**"]
  pull_request:
    branches: ["dev"]
jobs:
  test:
    runs-on: ubuntu-latest  # 运行环境：Ubuntu 服务器
    steps:
      - name: Checkout code  # 步骤1：拉取仓库代码
        uses: actions/checkout@v4
      - name: Set up Python 3.12  # 步骤2：配置 Python 环境
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"  # 与 Dockerfile 一致
      - name: Install dependencies  # 步骤3：安装依赖
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run tests  # 步骤4：执行测试
        run: pytest tests/test_app.py -v  # 显示详细测试日志
